# SITE CONFIGURATION
baseurl: "/rtros-documentation" # the subpath of your site, e.g. /blog/
url: "https://master-coro.github.io" # the base hostname & protocol for your site

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: ROS and Real-Time Capabilities
  avatar: 
  gravatar: # Email MD5 hash
  description: "An academic project from Ecole Centrale de Nantes by Sampreet Sarkar and Erwin Lejeune. About ROS, Linux/Xenomai and Real-Time Systems" # used by search engines

  # Header and footer text
  header_text: >
     <h1>Bringing Real-Time Capabilities to ROS.</h1>
     <p>Exploring the options on how to implement a real-time ROS Node using ROS + Linux/Xenomai</p>
  header_text_feature_image:
  footer_text: >
   Powered by <a href="http://jekyllrb.com">Jekyll</a> with <a href="https://rohanchandra.github.io/project/type/">Type Theme</a>

  # Icons
  rss: false
  email_address: "git.erts@gmail.com" # Full email address, e.g. "sam@example.com"
  behance:
  bitbucket:
  dribbble: 
  facebook: 
  flickr:
  github: "master-coro"
  google_plus:
  instagram:
  linkedin:  # Full URL
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter:
  wordpress:
  youtube:

  # Scripts
  google_analytics: # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname:
  katex: true # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Continue reading"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# COLLECTIONS
collections:
  portfolio:
    output: true

# BUILD SETTINGS
markdown: kramdown
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-paginate]
